import { ThemeProvider } from "@/components/theme-provider";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "../globals.css";
import { locales } from "@/lib/constants/locales";
import MainLayout from "@/components/main-layout";

const inter = Noto_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
